coverage:
  precision: 2
  round: down
  range: "45...100"
  status:
    project:
      default:
        target: 45%
        threshold: 0%
        base: auto
        if_not_found: failure
        if_ci_failed: error
        informational: false
        only_pulls: false
    patch: off
ignore:
  - "pkg/mocks"
  - "mock_*.go"
  - "*_test.go"